version: "3.5"

services:

  postgres:
    image: postgres
    volumes:
      - ./postgres/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
    environment:
      POSTGRES_DB: marina_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    restart: unless-stopped
   
  register:
    container_name: register_spring_boot
    depends_on:
      - postgres
    build:
      context: ./register
      dockerfile: Dockerfile
    image: my-register:latest
    restart: always
    ports:
      - 8761:8761